M48
; DRILL file {KiCad (6.0.0-0)} date Wednesday, March 30, 2022 at 03:47:30 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-30T15:47:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X5.2992Y-2.9498
X5.2992Y-4.8396
X6.5984Y-2.9498
X6.5984Y-4.8396
T0
M30
